<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\MorphTo;
use Illuminate\Support\Facades\Storage;

class Document extends Model
{
    use HasFactory;

    protected $fillable = ['path', 'transaction_type', 'transaction_id'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::deleting(function ($document) {
            if (static::where('path', $document->path)->exists()) {
                Storage::disk('public')->delete($document->path);
            }
        });
    }

    public function transaction(): MorphTo
    {
        return $this->morphTo();
    }
}
