<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\MorphTo;
use Illuminate\Database\Eloquent\Relations\Relation;
use Illuminate\Support\Facades\Storage;

//Relation::morphMap([
//    'User'      => 'App\Models\User',
//    'Employee'  => 'App\Models\Office\Employee',
//]);

class Photo extends Model
{
    use HasFactory;

    protected $fillable = ['path', 'transaction_type', 'transaction_id'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::deleting(function ($photo) {
            if (static::where('path', $photo->path)->exists()) {
                Storage::disk('public')->delete($photo->path);
            }
        });
    }

    public function transaction(): MorphTo
    {
        return $this->morphTo();
    }
}
